"""empty message

Revision ID: cb9b828fd687
Revises: 68e2974459fe
Create Date: 2021-05-18 12:19:08.544853

"""
from alembic import op
import sqlalchemy as sa
import jembe_auth_demo


# revision identifiers, used by Alembic.
revision = 'cb9b828fd687'
down_revision = '68e2974459fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', jembe_auth_demo.models.auth.SaFile(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
